from api.prompts.student_content_prompts import (
    PATHWAY_GENERATION_PROMPT,
    QUIZ_GENERATION_PROMPT,
    MISCONCEPTION_ANALYSIS_PROMPT,
    ADAPTIVE_RECOMMENDATION_PROMPT,
)

__all__ = [
    "PATHWAY_GENERATION_PROMPT",
    "QUIZ_GENERATION_PROMPT",
    "MISCONCEPTION_ANALYSIS_PROMPT",
    "ADAPTIVE_RECOMMENDATION_PROMPT",
]
